#!/bin/bash

cd "$(dirname "$0")"
diff -Nru a b > pacman-glib.patch

OLDMD5="$(md5sum packagekit/pacman-glib.patch | cut -d' ' -f1)"
NEWMD5="$(md5sum pacman-glib.patch | cut -d' ' -f1)"

cd packagekit
mv ../pacman-glib.patch . && sed -re "s/$OLDMD5/$NEWMD5/" -i PKGBUILD && makepkg "$@"
